from .AlexNet import AlexNet
from .UNet3D import UNet3D
from .MultiscaleUNet3D import MultiscaleUNet3D
from .exercise_rnn import exercise_rnn
from .LinearRegression import LinearRegression
from .ModuleTest1 import ModuleTest1
from .ModuleTest2 import ModuleTest2
from .ModuleTest3 import ModuleTest3
from .ModuleTest4 import ModuleTest4
from .ModuleTest5 import ModuleTest5
from .ModuleTest6 import ModuleTest6
from .UNet3D_Aneu import UNet3D_Aneu
from .ResUnet import ResUnet
from .NewResUnet1 import NewResUnet1
from .Resnet import Resnet
